apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  generation: 1
  name:  meu-nginx
  namespace: default
  labels:
    name:  meu-nginx
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run:  nginx
    spec:
      containers:
      - image:  nginx
        imagePullPolicy: Always
        name:  nginx
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:  
  labels:
    name: meu-nginx
  name: meu-nginx
  namespace: default
spec:  
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32590 #aonde vou acessar a porta externa, so consegui entre 30000 32676
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
