apiVersion: v1
kind: LimitRange # tipo
metadata:
  name: limitando-recursos # nome dele
spec:
  limits:
  - default:
      cpu: 1 # total
      memory: 256Mi # total
    defaultRequest: #o quanto que ele vai garantir
      cpu: 0.5
      memory: 128Mi
    type: Container  